export const prompts: string[] = [
  "Low-poly stylized treasure chest overflowing with shiny gold coins, worn wood texture, metal reinforcements, mobile fantasy game asset",
  "Photorealistic antique wooden chair with red cushioned seat, baroque-style carved backrest, optimized for interior archviz scenes",
  "Cyberpunk back-alley at night, wet pavement, neon kanji signs, exposed pipes, trash bins, atmospheric fog, flickering dynamic lights",
  "Cozy medieval blacksmith forge interior with stone furnace, iron tools, anvil, and a glowing half-forged sword on wooden workbench, game environment prop",
  "High-resolution stainless steel electric kettle with black ergonomic handle, photoreal finish, isolated on white background for product rendering",
  "Futuristic smartwatch with transparent curved OLED screen, minimal UI glow, silver alloy body, concept design presentation-ready",
  "Cartoon-style robot with glossy spherical torso, two jointed claw arms, single glowing camera eye, clean rig-friendly topology",
  "Fantasy elf archer with slender build, pointed ears, leather armor, wooden bow, quiver, neutral pose, topology for animation and rigging",
  "Retro-futuristic hovercar with floating suspension, chrome trims, glowing blue rear thrusters, sleek body, optimized for stylized racing game",
  "Highly detailed sci-fi spaceship cockpit interior with illuminated control panels, digital HUDs, pilot seat, joystick controls, cinematic-quality",
  "Low-poly stylized campsite scene with canvas tent, animated campfire, circular log seats, surrounding pine trees, top-down game view",
  "Isometric food truck with exaggerated features, pastel colors, open side window, kitchen interior details, perfect for casual mobile game",
  "Fantasy alchemy potion bottle with glowing blue liquid, floating sparkles inside, ornate glass design with cork stopper, isolated on black",
  "Cartoonish flying UFO with metallic disc body, blinking perimeter lights, transparent dome with green alien pilot, mid-flight pose",
  "Hyper-detailed bonsai tree with winding trunk, small textured leaves, soil in decorative ceramic pot, photogrammetry-style realism",
  "Stylized coral reef diorama with vibrant fish, animated bubbles, waving seaweed, ambient caustic lighting, optimized for underwater VR scene",
  "Realistic mushroom cluster on forest floor with earthy base, moist textures, moss patches, HDRI lighting for PBR workflows",
  "Giant sunflower plant model with high-res yellow petals, textured stem, large green leaves, photoreal scale, AR and mobile-friendly",
  "Aggressive orc warrior in detailed armor plates, tusks, rugged textures, massive battle axe, mid-roar pose, game-ready rig",
  "Chibi wizard character with oversized robe, glowing staff, flowing beard, magical aura orb, stylized textures, optimized for mobile RPG",
  "Zero-gravity astronaut with highly reflective helmet, NASA-style space suit, floating pose, Earth reflection in visor, cinematic render",
  "Stylized zombie chef with exaggerated apron, cartoon cleaver, exposed cartoon brain, comedic horror vibe, rig-ready topology",
  "Traditional Japanese tea house exterior and interior, wooden sliding doors, tatami mats, hanging paper lanterns, tranquil garden view",
  "Miniature medieval castle tower with stone bricks, worn battlements, waving flags, moss growth, isolated diorama-ready model",
  "Modern glass house architecture with open plan layout, minimalist furniture, surrounding landscaped garden, real-time visualization ready",
  "Abandoned subway tunnel with graffiti, broken fluorescent lights, damp concrete walls, scattered trash, post-apocalyptic detail",
  "Photoreal DSLR camera model with detachable lens, detailed buttons, textured dials, viewfinder and screen, studio lighting setup",
  "Floating sci-fi holographic UI console with interactive glowing panels, animated widgets, transparent projection frames, game HUD asset",
  "Mechanical steampunk gear assembly with spinning brass cogs, pistons, ornate pipes, looping mechanical animations, engine prop",
  "High-poly samurai katana with engraved steel blade, silk-wrapped hilt, detailed leather sheath, posed for weapon showcase",
];
