on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (without updating lock file)
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Run build
        run: pnpm run build
